### ISSUE TITLE
Could not get working with Enterprise Connect

### ISSUE THREAD

**Issue by ddcdennisb** [pbowden-msft/SignInHelper#3]
I kept getting the error: >>WARNING - Could not retrieve naming context
>>ERROR - Could not detect UPN.

After looking through the script, I found that if Enterprise Connect was Detected, there was no function to find the UPN.  So I added the following function and if statement to the main process.  It is working now.

Line 238:
## Get the UPN from Enterprise Connect
function GetUPNfromEnterpriseConnect {
	local ECUPN=$(${CMD_PREFIX} "/Applications/Enterprise Connect.app/Contents/SharedSupport/eccl" -a userPrincipalName | awk '/userPrincipalName:/{print $NF}' 2> /dev/null)
	if [ "$ECUPN" == "" ]; then
		echo "0"
	else
		echo "$ECUPN"
	fi
}

and Line 342:
## If we haven't got a UPN yet, see if we can get it from Enterprise Connect
if [ "$UPN" == "0" ] && [ "$EC" == "1" ]; then
	UPN=$(GetUPNfromEnterpriseConnect)
	if [ ! "$UPN" == "0" ]; then
		echo ">>INFO - Found UPN from Enterprise Connect: $UPN"
		SetPrefill "$UPN"
		exit 0
	else
		echo ">>WARNING - Could not retrieve UPN from Enterprise Connect"
	fi
fi

**Comment by pbowden-msft** [comment]
Hi Dennis, many thanks for the awesome suggestions! I've incorporated them into v1.1, which I just published.

Thanks again!
