### ISSUE TITLE
Can this be used without AD or Kerbose

### ISSUE THREAD

**Issue by kylejericson** [pbowden-msft/SignInHelper#4]
I was wondering if I could do a API call to jamf to get the username in user location field for the Mac and add on the @mydomain.com to generate the UPN. Do you think this will work?

**Comment by pbowden-msft** [comment]
@kylejericson yeah, should be possible. If you haven't seen it already, also take a look at Bill's post at https://jamf.it/one-click where he uses the $EMAIL variable in a Config Profile to produce a similar result.
